---
# tasks file for role

- name: Ensure group exists with correct gid
  ansible.builtin.group:
    name: "{{ mytoolsapi_group }}"
    state: present
    gid: "{{ mytoolsapi_gid }}"

- name: Ensure user exists with correct uid and group
  ansible.builtin.user:
    name: "{{ mytoolsapi_user }}"
    comment: mytoolsapi user
    system: true
    uid: "{{ mytoolsapi_uid }}"
    group: admin

- name: Clone the mytoolsapi git repository
  ansible.builtin.git:
    repo: "{{ mytoolsapi_gitsource}}"
    dest: "{{ mytoolsapi_dir }}"

- name: Fix permissions on the git destination.
  file:
    path: "{{ mytoolsapi_dir }}"
    state: directory
    owner: "{{ mytoolsapi_user }}"
    group: "{{ mytoolsapi_group }}"
    recurse: true
    mode: 0755

- name: Install mytoolsapi with poetry
  become: true
  become_user: '{{ mytoolsapi_user }}'
  chdir: "{{ mytoolsapi_dir }}"
  shell: poetry install
