---
# tasks file for role

- name: Deploy the MyToolsAPI service
  when: mytoolsapi_configure == true
  tags: mytoolsapi
  block:
    - name: Ensure group exists with correct gid
      ansible.builtin.group:
        name: "{{ mytoolsapi_group }}"
        state: present
        gid: "{{ mytoolsapi_gid }}"

    - name: Ensure user exists with correct uid and group
      ansible.builtin.user:
        name: "{{ mytoolsapi_user }}"
        comment: mytoolsapi user
        system: true
        uid: "{{ mytoolsapi_uid }}"
        group: "{{ mytoolsapi_group }}"

    - name: Create the directory for mytoolsapi
      ansible.builtin.file:
        path: "{{ mytoolsapi_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ mytoolsapi_user }}"
        group: "{{ mytoolsapi_group }}"

    - name: Clone the mytoolsapi git repository
      ansible.builtin.git:
        repo: "{{ mytoolsapi_gitsource}}"
        dest: "{{ mytoolsapi_dir }}"
      become: yes
      become_user: "{{ mytoolsapi_user }}"

    - name: Install mytoolsapi with poetry
      ansible.builtin.command: "{{ mytoolsapi_poetry_path }} install"
      become: yes
      become_user: "{{ mytoolsapi_user }}"
      args:
        chdir: "{{ mytoolsapi_dir }}"

    - name: Install required packages
      apt:
        name: "{{ mytoolsapi_apt_packages }}"
        state: present
